### ISSUE TITLE
Error Running Script on Windows 11

### ISSUE THREAD

**Issue by pcwzrd13** [theophile/SuperSlicer_to_Orca_scripts#28] opened 2024-03-10 14:46 UTC
I'm trying to run this on Windows 11 with Strawberry Pearl but I'm getting the following error:

```
Bareword found where operator expected (Missing semicolon on previous line?) at superslicer_to_orca.pl line 11, near "data"
Can't modify numeric lt (<) in scalar assignment at superslicer_to_orca.pl line 11, near "data"
syntax error at superslicer_to_orca.pl line 11, near "data"
Execution of superslicer_to_orca.pl aborted due to compilation errors.
``` 

Any idea what the problem is?

**Comment by theophile** [comment] 2024-03-10 17:04
Duplicate of #12

**Closed by theophile** 2024-03-10 17:04 UTC
